### ISSUE TITLE
JSZip used in dist\webpackSalesforcePlugin.js while not added to dependencies.

### ISSUE THREAD

**Issue by ichizos** [nadrees/webpack-salesforce-plugin#4]
Error while running build using Webpack with this plugin.

```
Error: Cannot find module 'jszip'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (*\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:8:1286)
    at n (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:183)
    at Object.module.exports.i (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:3:26504)
    at n (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:183)
    at Object.<anonymous> (*\frontend\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:761)
    at n (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:183)
    at *\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:270
    at Object.<anonymous> (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:275)
    at Module._compile (*\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (*\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (*\webpack.common.js:7:26)
    at Module._compile (*\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (*\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (*\webpack.prod.js:1:78)
    at Module._compile (*\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by ichizos** [comment]
When installed JSZip in v2.6.1, build run successfully. From JSzip-v.3.*.* another error is thrown:

```
Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.
    at new JSZip (*\node_modules\jszip\lib\index.js:14:15)
    at new t.exports (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:3:26557)
    at t.value (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:2318)
    at *\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:1660
    at Array.map (<anonymous>)
    at t.value (*\node_modules\webpack-salesforce-plugin\dist\webpackSalesforcePlugin.js:1:1635)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (*\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (*\node_modules\tapable\lib\Hook.js:154:20)
    at asyncLib.forEachLimit.err (*\node_modules\webpack\lib\Compiler.js:482:27)
    at *\node_modules\neo-async\async.js:2818:7
    at done (*\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (*\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at outputFileSystem.writeFile.err (*\node_modules\webpack\lib\Compiler.js:464:33)
    at *\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
```
